# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "551a199221a7521e32de9e48586bcef0"
name = "LV-VIP-APP"
application_url = "https://backend.lucvincent.com"
embedded = true
handle = "lv-vip-app"

[app_proxy]
url = "https://backend.lucvincent.com"
subpath = "apps/vip"
prefix = "apps"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "subscription_contracts/create" ]
  uri = "/webhooks/subscription_contracts/create"

  [[webhooks.subscriptions]]
  topics = [ "subscription_contracts/update" ]
  uri = "/webhooks/subscription_contracts/update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/compliance"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_payment_methods,read_customers,read_discounts,read_orders,read_own_subscription_contracts,read_price_rules,read_products,write_customers,write_discounts,write_orders,write_own_subscription_contracts,write_price_rules"

[auth]
redirect_urls = [ "https://backend.lucvincent.com/auth/callback" ]

[pos]
embedded = false
