# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "551a199221a7521e32de9e48586bcef0"
name = "LV-VIP-APP"
application_url = "https://localhost:3000"
embedded = true
handle = "lv-vip-app"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_payment_methods,read_customers,read_discounts,read_orders,read_own_subscription_contracts,read_price_rules,read_products,write_customers,write_discounts,write_orders,write_own_subscription_contracts,write_price_rules"

[auth]
redirect_urls = [ "https://localhost:3000/auth/callback" ]

[pos]
embedded = false
