# Learn more about configuring your Customer Account UI extension at
# https://shopify.dev/docs/api/customer-account-ui-extensions

api_version = "2025-04"

[[extensions]]
type = "ui_extension"
name = "Mes points VIP"
handle = "vip-points-display"

[[extensions.targeting]]
module = "./src/BlockExtension.tsx"
target = "customer-account.order-index.block.render"

[extensions.capabilities]
network_access = true
